### ISSUE TITLE
Problem with Maybank Channel on Android

### ISSUE THREAD

**Issue by syqal** [MOLPay/molpay-mobile-xdk-nativescript#2]
Hi,

We've managed to integrate this on our app. It works nicely for both Android & iOS. However, when user select Maybank2u / Mybank2u(FPX), the payment did not go through.

The following is the error we get when debugging:
```
chromium: [INFO:CONSOLE(0)] "Upcoming versions will block content-initiated top frame navigations to data: URLs. For more 
information, see https://goo.gl/BaZAea.", source: file:///data/data/com.myinterfacehub.app/files/app/molpay-mobile-xdk-www
/#/finalizingpayment (0)                                                                                                  
chromium: [INFO:CONSOLE(1157)] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or
 'navigator.webkitPersistentStorage' instead.", source: https://www.maybank2u.com.my/mbb/m2u/m9000/m2uFpxXmlReceiver.do (1
157)                                                                                                                      
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.callJSMethodNative(Native Method)                      
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)          
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)                    
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1047)                        
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1028)                        
08-11 10:53:07.872 18082 18082 W System.err:    at com.tns.Runtime.callJSMethod(Runtime.java:1018)                        
08-11 10:53:07.872 18082 18082 W System.err:    at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedErr
or2(WebViewContentsClientAdapter.java:235)                                                                                
08-11 10:53:07.872 18082 18082 W System.err:    at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.h
andleMessage(AwContentsClientCallbackHelper.java:38)                                                                      
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)              
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)  
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)            
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:1047)                
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:1028)                
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:1018)                
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at com.android.webview.chromium.WebViewContentsClientAdapter.onRec
eivedError2(WebViewContentsClientAdapter.java:235)                                                                        
08-11 10:53:07.875 18082 18082 E AndroidRuntime:        at org.chromium.android_webview.AwContentsClientCallbackHelper$MyH
andler.handleMessage(AwContentsClientCallbackHelper.java:38)
```
So far we only have problem with Maybank channel.

Please help to check on this.

Thanks!

**Comment by LeowWH** [comment]
Hi @syqal ,

Thanks for using our xdk. We might need you to provide us the screenshot also on which point it crash the app. We will start investigate on this issue after you provide us the screenshot or you also can explain to us which and what you have seen on the screen. We need this information to further investigate the issue thanks.

"**So far we only have problem with Maybank channel.**" from this statement mean other channels don't have this problem am i right?

**Comment by syqal** [comment]
Hi @LeowWH 

Here are some of the screenshot:

**1st screenshot:  After we select the channel**
![ss-01 custom](https://user-images.githubusercontent.com/7812080/29204193-2c102494-7ea8-11e7-9486-01f58732c4d2.png)

**2nd screenshot: After hit Proceed**
![ss-02 custom](https://user-images.githubusercontent.com/7812080/29204194-2c1878a6-7ea8-11e7-9781-ceefa310b4b0.png)

I couldn't get the next screenshot because its there just for a very short time. But the screen is where you need to enter your maybank2u username. That's when the app crash.

Yup,  we don't have this problem with other channels.

Thanks in advance.

**Comment by LeowWH** [comment]
Hi @syqal ,
Since we cannot reproduce your problem we will need a detail tech discussion so you can reach me on Skype to more convenient communication.  Thanks.

Skype ID : lelouchliew93@hotmail.com
